BaiTap26_11/BaiTap/Models/Hang.cs
namespace BaiTap.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.ComponentModel;
    [Table("Hang")]
    public partial class Hang
    {
        [Key]
        [StringLength(10)]
        [Required(ErrorMessage = "Mã hàng không được để trống")]
        [DisplayName("Mã hàng")]
        public string MaHang { get; set; }

        [Required(ErrorMessage = "Mã nhà cung cấp không được để trống")]
        [StringLength(10)]
        [DisplayName("Mã NCC")]
        public string MaNCC { get; set; }

        [Required(ErrorMessage = "Tên hàng không được để trống")]
        [StringLength(255)]
        [DisplayName("Tên hàng")]
        public string TenHang { get; set; }

        [Column(TypeName = "numeric")]
        [DisplayName("Gía")]
        public decimal? Gia { get; set; }

        [Column(TypeName = "numeric")]
        [DisplayName("Lượng có")]
        public decimal LuongCo { get; set; }

        [StringLength(1000)]
        [Column(TypeName = "text")]
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }


        [DisplayName("Chiết khấu")]
        public decimal? ChietKhau { get; set; }

        [StringLength(100)]
        [DisplayName("Hình ảnh")]
        public string HinhAnh { get; set; }

        public virtual Nha_CC Nha_CC { get; set; }
    }
}

BaiTap26_11/BaiTap/Controllers/HangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BaiTap.Models;

namespace BaiTap.Controllers
{
    public class HangsController : Controller
    {
        private fShopDB db = new fShopDB();

        // GET: Hangs
        public ActionResult Index()
        {
            var hangs = db.Hangs.Include(h => h.Nha_CC);
            return View(hangs.ToList());
        }

        // GET: Hangs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }
            return View(hang);
        }

        // GET: Hangs/Create
        public ActionResult Create()
        {
            ViewBag.MaNCC = new SelectList(db.Nha_CC, "MaNCC", "TenNCC");
            return View();
        }

        // POST: Hangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHang,MaNCC,TenHang,Gia,LuongCo,MoTa,ChietKhau,HinhAnh")] Hang hang)
        {
            if (ModelState.IsValid)
            {
                hang.HinhAnh = "";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    //user namespace called:system.io
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UpLoadPath = Server.MapPath("~/wwwroot/WineImages/" + FileName);
                    f.SaveAs(UpLoadPath);                 
                    hang.HinhAnh = FileName;

                }
                db.Hangs.Add(hang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaNCC = new SelectList(db.Nha_CC, "MaNCC", "TenNCC", hang.MaNCC);
            return View(hang);
        }

        // GET: Hangs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNCC = new SelectList(db.Nha_CC, "MaNCC", "TenNCC", hang.MaNCC);
            return View(hang);
        }

        // POST: Hangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHang,MaNCC,TenHang,Gia,LuongCo,MoTa,ChietKhau,HinhAnh")] Hang hang)
        {
            if (ModelState.IsValid)
            {
                hang.HinhAnh = "";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    //user namespace called:system.io
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UpLoadPath = Server.MapPath("~/wwwroot/WineImages/" + FileName);
                    f.SaveAs(UpLoadPath);
                    hang.HinhAnh = FileName;
                }
                db.Entry(hang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNCC = new SelectList(db.Nha_CC, "MaNCC", "TenNCC", hang.MaNCC);
            return View(hang);
        }

        // GET: Hangs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }
            return View(hang);
        }

        // POST: Hangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Hang hang = db.Hangs.Find(id);
            try
            {
                db.Hangs.Remove(hang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch   (Exception ex)
            {
                ViewBag.Error = "Không xóa được bản ghi này " + ex.Message;
                return View("Delete",hang);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaiTap26_11/BaiTap/Views/Hangs/Create.cshtml
@model BaiTap.Models.Hang

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Hangs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Hang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, "MaNCC", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuongCo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuongCo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LuongCo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChietKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChietKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChietKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })*@
                <img id="output" class="img-rounded" alt="ảnh" width="100" height="200" src="~/wwwroot/WineImages/h0.png" />
                <p><label for="ufile" style="cursor:pointer;">Chọn file ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display:none;" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@if (ViewBag.error != null)
{
    <br />
    <div class="alert-danger" role="alert">@ViewBag.error</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

BaiTap26_11/BaiTap/Views/Hangs/Delete.cshtml
@model BaiTap.Models.Hang

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nha_CC.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nha_CC.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LuongCo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LuongCo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChietKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChietKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
@if (ViewBag.error != null)
{
    <br />
    <div class="alert-danger" role="alert">@ViewBag.error</div>
}

BaiTap26_11/BaiTap/Views/Hangs/Details.cshtml
@model BaiTap.Models.Hang

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Hang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nha_CC.TenNCC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nha_CC.TenNCC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LuongCo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LuongCo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChietKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChietKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaHang }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BaiTap26_11/BaiTap/Views/Hangs/Edit.cshtml
@model BaiTap.Models.Hang

@{
    ViewBag.Title = "Edit";
    var ImagePath = "~/anh/WineImages/" + Model.HinhAnh;
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Hangs", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Hang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaHang)

        <div class="form-group">
            @Html.LabelFor(model => model.MaNCC, "MaNCC", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNCC", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuongCo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuongCo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LuongCo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChietKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChietKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChietKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })*@
                <img id="output" class="img-rounded" alt="ảnh" width="100" height="200" src="@Url.Content(@ImagePath)" />
                <p><label for="ufile" style="cursor:pointer;">Chọn file ảnh</label></p>
                <input name="ImageFile" id="ufile" type="file" style="display:none;" onchange="loadFile(event)" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@if (ViewBag.error != null)
{
    <br />
    <div class="alert-danger" role="alert">@ViewBag.error</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    var loadFile = function (event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

BaiTap26_11/BaiTap/Views/Hangs/Index.cshtml
@model IEnumerable<BaiTap.Models.Hang>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nha_CC.TenNCC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LuongCo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChietKhau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nha_CC.TenNCC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenHang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LuongCo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MoTa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ChietKhau)
        </td>
        <td>
            @{
                string ImagePath = "~/wwwroot/WineImages/" + item.HinhAnh;
            }
            <img src="@Url.Content(ImagePath)" width="300" class="img-thumbnail" />
            <br />
            @Html.DisplayFor(model => item.HinhAnh)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaHang.Trim() }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaHang.Trim() }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaHang.Trim() })
        </td>
    </tr>
}

</table>